### ISSUE TITLE
Running status not supported

### ISSUE THREAD

**Issue by krgri** [codecapers/Fluent-Behaviour-Tree#10]
The current version only supports Success and Failure return types.  The implementation assumes that all nodes will either end in Success or Failure on the first Tick.  Nodes that return a Running status are not explicitly re-visited on subsequent Ticks.

When re-visiting a node, if the return state is Running, the visit should be treated as if nothing changed until the Running node returns success or failure.  This means that parents of a running node should be marked as running when bubbling back up the tree.  Additionally, the currently running node should be remembered so that it can quickly be evaluated on following Ticks.  The only place where this would differ is in the ParallelNode type where there can be multiple nodes running simultaneously.

**Comment by aequasi** [comment]
This feels like a serious design flaw to me. Did you find a solution @krgri

**Comment by hyakugei** [comment]
I think you have a specific Behaviour Tree implementation in mind. Some BTs keep state between ticks, and return to "running" nodes. This is not a requirement for something to be a Behaviour Tree. It requires a different way of looking at how you layout your nodes is all. And maybe this implementation isn't for you, if you are looking for this specific behaviour. Good luck!

**Comment by aequasi** [comment]
https://i.imgur.com/VGuTGRk.png

It doesn't just "stay" on the current child node. It re-runs the entire tree up to that point, and then doesn't continue.

If theres no plan for this implementation to not maintain state between ticks, it should document that somewhere

**Comment by hyakugei** [comment]
Ah i see what you are talking about - i interpreted that differently. It "stays" on it in the sense that it never moves "past" in on subsequent ticks until it either succeeds or fails. But i can see that it can be taken to mean what you are thinking of, and the readme should probably be made more explicit.

**Comment by ashleydavis** [comment]
Sorry I'm not working on this project. Please fork it and modify as you need.
