### ISSUE TITLE
Sequence node evaluates every previous node in addition to the current node on Tick

### ISSUE THREAD

**Issue by wallacethefmh** [codecapers/Fluent-Behaviour-Tree#12]
I've just started working with the library so maybe I am missing something.

The documentation implies, but does not explicitly state, that only the current node is evaluated each tick in a Sequence node, which is not the case. Sequence nodes evaluate all child nodes previous to the current child node on each tick (assuming the previous child nodes succeeded). Documentation states that it "moves" to the next child node on success:

> Runs each child node in sequence. Fails for the first child node that fails. Moves to the next child when the current running child succeeds. Stays on the current child node while it returns running. Succeeds when all child nodes have succeeded.

**Comment by ashleydavis** [comment]
All nodes are evaluated.
