### ISSUE TITLE
Repeating?

### ISSUE THREAD

**Issue by Thraka** [codecapers/Fluent-Behaviour-Tree#3]
I'm new to this stuff but it seems like a really great w ay to do AI. However, I want say my driver to continually do these things. But it sounds like once a step is marked as successful, it won't be repeated. Your blog post doesn't handle repeating, but I assume that the VehicleRecycle stuff is the repeat. How does it work?

**Comment by Thraka** [comment]
They seem to repeat automatically. I'm not really sure I understand how the lifecycle of it works. Perhaps you can explain that too? Thanks :)

**Comment by ashleydavis** [comment]
Do you want to a behaviour to simply continue running? 

If that's the case you can return _BehaviourTreeStatus.Running_ and a behaviour will continue to run each update until you return _Success_ or _Failure_.

I really should add a repeater node as described in the following articles:
https://outforafight.wordpress.com/2014/07/15/behaviour-behavior-trees-for-ai-dudes-part-1/
http://guineashots.com/2014/08/15/an-introduction-to-behavior-trees-part-3/

I'd like to add this but I probably won't get to if for some time. You are welcome to fork the repo, make your changes, then submit a pull request and I'll merge them back in. You'll have to write unit-tests for any code that you add (TDD preferred), but please contribute and help improve this library.

**Comment by Thraka** [comment]
I'll start looking at the code more.

I think what was getting me is that I didn't understand that each action node is going to be run every single time through, right? There doesn't seem to be (for example the `SequenceNode`) an internal pointer which represents the current action. If the structure is like this:

```
Sequence
    Do  <-- complete
    Do  <-- running
    Do
```

Every time the sequence runs, it's still processing that first Do node. If some state changes in it and it no longer shortcuts out with `complete` then it will have technically run again, right?

Or really is the point of a behavior tree to evaluate everything all at once? I'm new to this stuff so I'm still trying to figure it out :)

**Comment by ashleydavis** [comment]
I believe that is the correct design, but possibly I am wrong. If you can find an example elsewhere of how it should work then I'll be happy to update it.

**Comment by Thraka** [comment]
I think both designs are right based on what you want, from what I read online. It was just me not realizing it would run like that as default.

**Comment by ashleydavis** [comment]
Ok, thanks for getting involved. Let me know if you have any other issues.
