### ISSUE TITLE
Sequence is not staying on Action when returning Running.

### ISSUE THREAD

**Issue by Cylindric** [codecapers/Fluent-Behaviour-Tree#5]
Hi. I'm trying to your your FBT in a Unity game fiddling around with, and I'm having trouble with my first tree. I have defined a sequence of actions for my AI character to perform, which involves looking for work, fetching materials for the job, and going to the job site before finally doing the work.

In my constructor I have the following tree:

           var builder = new BehaviourTreeBuilder();
            _tree = builder
                .Sequence("work-job")
                    .Do("get-next-job", t => GetNextJob_Action(t.deltaTime))
                    .Do("movesetup-move-to-jobsite", t=> SetupMoveToJobSite_Action(t.deltaTime))
                    .Do("move-to-jobsite", t =>MoveTowardsDestination_Action(t.deltaTime))
                    .Do("drop_stock", t => TransferStockToJob_Action(t.deltaTime))
                    .Do("do-work", t => DoWork_Action(t.deltaTime))
                .End()
                .Build();

In my update I call

            _tree.Tick(new TimeData(deltaTime));

The first two steps complete in one tick, as they are "setup" steps, so they always return a simple Success or Failure. The third step, 'move-to-jobsite' involves the character moving, so there's a bunch of time needed to wander about. That means the method `MoveTowardsDestination_Action()` returns "Running" for many ticks. 

What I'm finding though, is that when I return 'Running', the next tick returns to the 'get-next-job' action, and doesn't run the 'move-to-jobsite' action again.

If I put logging into each method, I see it running each step up to the move-to-jobsite one, which it never runs more than once.

In case it helps, the full [Character code is this one](https://github.com/Cylindric/Sim/blob/7d0a75b5df2c56c99253c6b36d92f26276b5dd80/UnitySources/Assets/Scripts/Model/Character.cs).

**Comment by Cylindric** [comment]
Just as a test, I tried replacing all the actions with stubs:

            _tree = builder
                .Sequence("work-job")
                    .Do("get-next-job", t => {
                        Debug.Log("get-next-job");
                        return BehaviourTreeStatus.Success;
                    })
                    .Do("movesetup-move-to-jobsite", t => {
                        Debug.Log("movesetup-move-to-jobsite");
                        return BehaviourTreeStatus.Success;
                    })
                    .Do("move-to-jobsite", t =>
                    {
                        Debug.Log("move-to-jobsite");
                        return BehaviourTreeStatus.Running;
                    })
                    .Do("drop_stock", t => {
                        Debug.Log("drop_stock");
                        return BehaviourTreeStatus.Success;
                    })
                    .Do("do-work", t => {
                        Debug.Log("do-work");
                        return BehaviourTreeStatus.Success;
                    })
                .End()
                .Build();

And my logs now show it spinning through these repeatedly:

	get-next-job
	movesetup-move-to-jobsite
	move-to-jobsite
	get-next-job
	movesetup-move-to-jobsite
	move-to-jobsite
	get-next-job
	movesetup-move-to-jobsite
	move-to-jobsite

I expected to see

	get-next-job
	movesetup-move-to-jobsite
	move-to-jobsite
	move-to-jobsite
	move-to-jobsite
	move-to-jobsite
	move-to-jobsite
	move-to-jobsite

**Comment by Cylindric** [comment]
I just found your closed issue #3 and it looks like this behaviour might be by design.

I have implemented a change in my fork that changes it, so it more closely reflects how I interpreted your description of Sequence, but I realise it's different to your interpretation. I'd like to submit it as a pull-request, but would you prefer it as a new type instead of Sequence, or just change Sequence?

**Comment by ashleydavis** [comment]
Thanks for your feedback. You are correct in thinking that behaviour trees are intended to work this way. Behaviour trees are very flexible and can undoubtedly do what you need, you might just need some practice understanding the various operations and how they can be composed to achieve the result you need.

The solution to your problem is to probably use a selector (like a switch statement) and a condition to disable the setup actions once the character is doing something.

Something like this might work for you:

var builder = new BehaviourTreeBuilder();
        _tree = builder
            .Selector("setup-or-work")
                .Sequence("setup-job")
                    // Fn returns true if the character neesd a job.
                   .Condition("needs-a-job", t => DoesCharacterNeedANewJob()) 
                   .Do("get-next-job", t => GetNextJob_Action(t.deltaTime))
                   .Do("movesetup-move-to-jobsite", t=> SetupMoveToJobSite_Action(t.deltaTime))
                .End()
                .Sequence("work-job")
                    .Do("move-to-jobsite", t =>MoveTowardsDestination_Action(t.deltaTime))
                    .Do("drop_stock", t => TransferStockToJob_Action(t.deltaTime))
                    .Do("do-work", t => DoWork_Action(t.deltaTime))
                .End()
            .End()
            .Build();

I have an [article](http://www.what-could-possibly-go-wrong.com/fluent-behavior-trees-for-ai-and-game-logic/) on this that might help you.

**Comment by Cylindric** [comment]
Yeah, I guess that would work too. I think the main root of the confusion is the statement "Stays on the current child node while it returns running." - it clearly doesn't stay on the node, as it runs all preceding nodes while the node returns running, so perhaps just a slight change of wording so it's not quite so surprising. That would've meant I would've immediately added some state to my methods, or a Selector as you say, and it all would've been fine.

**Comment by ashleydavis** [comment]
Thanks for pointing that out. Conceptually I think it is correct but maybe I haven't communicated it clearly.

If you like my work please consider sponsoring me on patreon: https://www.patreon.com/whatcouldpossiblygowrong

**Comment by Cylindric** [comment]
Yeah, I think I'm getting it now :) I guess the idea of traversing the
whole tree every time, is that you can make decisions at point A) that
maybe change or abort activity "later on" in the process. Now I'm just
trying to work out the logical return values from each step.

Your library is very elegant, and I was surprised how little there was - a
sign of a neat solution. I think it'll make my AI much simpler to
understand and change going forwards.

**Comment by Cylindric** [comment]
Thought I'd just let you know that I'm seeing the light :) My Character AI is now running nicely.

In case it's interesting (or useful to anyone in future-land), here's a graph of what I ended up with:
![graph](https://cloud.githubusercontent.com/assets/215695/17118703/b780d206-52b9-11e6-9f60-5f877868ba5b.png)

**Comment by ashleydavis** [comment]
Thanks Mark! I appreciate you posting the diagram.
